# Generated by Django 3.1.4 on 2020-12-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='image_gallery',
        ),
    ]
