# Generated by Django 2.1.7 on 2020-10-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200929_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='heading',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
