# Generated by Django 2.1.7 on 2020-10-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_services_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='heading',
        ),
    ]
