# Generated by Django 3.1.4 on 2020-12-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201213_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('application_form', models.FileField(blank=True, upload_to='Application')),
            ],
            options={
                'verbose_name': 'Application form',
                'verbose_name_plural': 'Application forms',
            },
        ),
    ]
