# Generated by Django 2.1.7 on 2020-10-21 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_services_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='heading',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
