# Generated by Django 2.1.7 on 2020-10-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201021_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='heading',
        ),
    ]
