# Generated by Django 2.1.7 on 2020-10-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_services_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='heading',
            field=models.CharField(default='Write your heading here ...', max_length=50),
        ),
    ]
