# Generated by Django 2.1.7 on 2020-10-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201021_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='heading',
        ),
    ]
